# --
# (c) Iver!
# Iván Jaimes <ivan.iver@gmail.com>
#
# This is a setup profile enviroment file for unix-like systems.
# See bash_rc or bash_profile for more information.

. ~/Config/dotfiles/bash/env
. ~/Config/dotfiles/bash/alias

source ~/Config/rvm.sh
. ~/Config/dotfiles/git/git-completion.bash
source ~/Config/dotfiles/git/git-prompt.sh
. ~/Config/dotfiles/bash/go_path
. ~/Config/dotfiles/bash/paths
source ~/Config/dotfiles/bash/go-complete.bash

# Uncomment this line if you want to load ssh-id
. ~/Config/dotfiles/bash/load_keys.sh

# [ -z "$SP1" ] && return

if [ -f ~/.profile ]; then
  . ~/.profile
fi

if type brew 2&>/dev/null; then
  source "$(brew --prefix)/etc/bash_completion"
else
  echo "run: brew install git bash-completion"
fi

eval "$(pyenv init -)"
