# --
# (c) Iver!
# Iván Jaimes <ivan.iver@gmail.com>
#
# This is a setup profile enviroment file for unix-like systems.
# See bash_rc or bash_profile for more information.

. ~/Config/dotfiles/bash/env
. ~/Config/dotfiles/bash/alias

. ~/Config/dotfiles/git/git-completion.bash
source ~/Config/dotfiles/git/git-prompt.sh
. ~/Config/dotfiles/bash/go_path
. ~/Config/dotfiles/bash/paths
source ~/Config/dotfiles/bash/go-complete.bash

# Uncomment this line if you want to load ssh-id
. ~/Config/dotfiles/bash/load_keys.sh

# [ -z "$SP1" ] && return

if [ -f ~/.profile ]; then
  . ~/.profile
fi

if type brew 2&>/dev/null; then
  source "$(brew --prefix)/etc/bash_completion"
else
  echo "run: brew install git bash-completion"
fi

eval "$(pyenv init -)"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/iver/Google/google-cloud-sdk/path.bash.inc' ]; then . '/Users/iver/Google/google-cloud-sdk/path.bash.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/iver/Google/google-cloud-sdk/completion.bash.inc' ]; then . '/Users/iver/Google/google-cloud-sdk/completion.bash.inc'; fi

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

export NVM_DIR="$(brew --prefix nvm)"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export PATH=$PATH:$HOME/.local/bin
powerline-daemon -q
POWERLINE_BASH_CONTINUATION=1
POWERLINE_BASH_SELECT=1
# . /Users/iver/.local/lib/python3.7/site-packages/powerline/bindings/bash/powerline.sh
#. /Users/iver/Library/Python/3.8/lib/python/site-packages/powerline/bindings/bash/powerline.sh


# The next line updates PATH for the Google Cloud SDK.
if [ -f '/usr/local/google-cloud-sdk/path.bash.inc' ]; then . '/usr/local/google-cloud-sdk/path.bash.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/usr/local/google-cloud-sdk/completion.bash.inc' ]; then . '/usr/local/google-cloud-sdk/completion.bash.inc'; fi

export PATH="$HOME/.cargo/bin:$PATH"

eval "$(direnv hook bash)"

. $(brew --prefix asdf)/asdf.sh
. $(brew --prefix asdf)/etc/bash_completion.d/asdf.bash

source ~/Config/rvm.sh
export PATH="/usr/local/opt/postgresql/bin:$PATH"
[[ -s "$HOME/.kiex/scripts/kiex" ]] && source "$HOME/.kiex/scripts/kiex"
