#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

# --
# (c) Iver!
# Iván Jaimes <ivan.iver@gmail.com>
#
# This is a setup profile enviroment file for unix-like systems.
# See bash_rc or bash_profile for more information.

DOT_FILES=~/Config/dotfiles

load_env_files() {
  # shellcheck source=/dev/null
  . "${DOT_FILES}/bash/env"
  # shellcheck source=/dev/null
  . "${DOT_FILES}/bash/alias"

  # shellcheck source=/dev/null
  . "${DOT_FILES}/git/git-completion.bash"
  # shellcheck source=/dev/null
  source ${DOT_FILES}/git/git-prompt.sh
  # shellcheck source=/dev/null
  . ${DOT_FILES}/bash/go_path
  # shellcheck source=/dev/null
  . ${DOT_FILES}/bash/paths
  # shellcheck source=/dev/null
  source ${DOT_FILES}/bash/go-complete.bash
}

load_ssh_keys() {
  # shellcheck source=/dev/null
  [[ -f ${DOT_FILES}/bash/load_keys.sh ]]  && . ${DOT_FILES}/bash/load_keys.sh
}


if type brew 2&>/dev/null; then
  source "$(brew --prefix)/etc/bash_completion"
else
  echo "run: brew install git bash-completion"
fi

eval "$(pyenv init -)"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/iver/Google/google-cloud-sdk/path.bash.inc' ]; then . '/Users/iver/Google/google-cloud-sdk/path.bash.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/iver/Google/google-cloud-sdk/completion.bash.inc' ]; then . '/Users/iver/Google/google-cloud-sdk/completion.bash.inc'; fi

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

export NVM_DIR="$(brew --prefix nvm)"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export PATH=$PATH:$HOME/.local/bin
powerline-daemon -q
POWERLINE_BASH_CONTINUATION=1
POWERLINE_BASH_SELECT=1
# . /Users/iver/.local/lib/python3.7/site-packages/powerline/bindings/bash/powerline.sh
#. /Users/iver/Library/Python/3.8/lib/python/site-packages/powerline/bindings/bash/powerline.sh


export PATH="$HOME/.cargo/bin:$PATH"

eval "$(direnv hook bash)"

. $(brew --prefix asdf)/asdf.sh
. $(brew --prefix asdf)/etc/bash_completion.d/asdf.bash

source ~/Config/rvm.sh
export PATH="/usr/local/opt/postgresql/bin:$PATH"
[[ -s "$HOME/.kiex/scripts/kiex" ]] && source "$HOME/.kiex/scripts/kiex"

# heroku autocomplete setup
HEROKU_AC_BASH_SETUP_PATH=/Users/iver/Library/Caches/heroku/autocomplete/bash_setup && test -f $HEROKU_AC_BASH_SETUP_PATH && source $HEROKU_AC_BASH_SETUP_PATH;

main() {
  load_env_files

  if [ -f ~/.profile ]; then
    . ~/.profile
  fi
}

main
