#!/usr/bin/env bash
# --
# (c) Iver!
# Iván Jaimes <ivan.iver@gmail.com>
#
# This is a setup profile enviroment file for unix-like systems.
# See bash_rc or bash_profile for more information.

# set -o errexit
set -o nounset
set -o pipefail

# export LC_ALL=en_US.UTF-8
# export LANG=en_US.UTF-8

CONF_FILES=~/Config
ENV_FILES="${CONF_FILES}/env"
DOT_FILES="${CONF_FILES}/dotfiles"
PATH_FILES="${CONF_FILES}/env/paths"
UTILS_PATH="${CONF_FILES}/scripts/utils"

load_env_files() {
  # shellcheck source=/dev/null
  . "${ENV_FILES}/env"
  # shellcheck source=/dev/null
  . "${ENV_FILES}/alias"
  # shellcheck source=/dev/null
  . "${PATH_FILES}/pathrc" "${PATH_FILES}"
  # shellcheck source=/dev/null
  . "${ENV_FILES}/git/git-completion.bash"
  # shellcheck source=/dev/null
  source ${ENV_FILES}/git/git-prompt.sh
}

load_ssh_keys() {
  # shellcheck source=/dev/null
  if [[ -f ${UTILS_PATH}/ssh_keys ]]; then
    . ${UTILS_PATH}/ssh_keys
    read_on_init
  fi
}

brew_autocomplete() {
  if type brew 2&>/dev/null; then
    source "$(brew --prefix)/etc/bash_completion.d/*"
  else
    echo "run: brew install git bash-completion"
  fi
}

pyenv_init() {
  eval "$(pyenv init -)"
}

google_sdk_init() {
  # The next line updates PATH for the Google Cloud SDK.
  if [ -f '/Users/iver/Google/google-cloud-sdk/path.bash.inc' ]; 
    then . '/Users/iver/Google/google-cloud-sdk/path.bash.inc'; 
  fi

  # The next line enables shell command completion for gcloud.
  if [ -f '/Users/iver/Google/google-cloud-sdk/completion.bash.inc' ];
    then . '/Users/iver/Google/google-cloud-sdk/completion.bash.inc'; 
  fi
}

nvm_init() {
  export NVM_DIR="$(brew --prefix nvm)"
  # loads nvm
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
  # loads nvm bash_completion
  [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
}

powerline_init() {
  export PATH=$PATH:$HOME/.local/bin
  powerline-daemon -q
  POWERLINE_BASH_CONTINUATION=1
  POWERLINE_BASH_SELECT=1

  # . ${HOME}/.local/lib/python3.7/site-packages/powerline/bindings/bash/powerline.sh
  #. ${HOME}/Library/Python/3.8/lib/python/site-packages/powerline/bindings/bash/powerline.sh
}

direnv_init() {
  eval "$(direnv hook bash)"
}

asdf_init() {
  local ASDF_PATH
  ASDF_PATH="$(brew --prefix asdf)"

  . ${ASDF_PATH}/libexec/asdf.sh
  . ${ASDF_PATH}/etc/bash_completion.d/asdf.bash
}

main() {
  load_env_files
  load_ssh_keys
  # brew_autocomplete
  # pyenv_init
  # google_sdk_init
  # nvm_init
  # powerline_init
  # direnv_init
  asdf_init

  if [ -f ~/.profile ]; then
    . ~/.profile
  fi
}

main
