#!/usr/bin/env bash

# go_path
# --
# (c) Iver!
# Iván Jaimes <iver@iver.mx>
# --
# Goal: add go locations to path

go_2_path() {
  [ -d /usr/local/golang/go ] && export GOROOT=/usr/local/golang/go
  [ -d ${HOME}/Workspace/go ] && export GOPATH=${HOME}/Workspace/go
  [ -d ${GOPATH}/bin ] && export GOBIN=${GOPATH}/bin
  [ -d ${GOROOT}/bin ] && export LPATH=${GOROOT}/bin
  LPATH=${LPATH}:${GOBIN}
}

go_2_path
