#!/usr/bin/env bash

# java_path
# --
# (c) Iver!
# Iván Jaimes <iver@iver.mx>
# --
# Goal: add java locations to path

java_2_path() {
  local J_VERSION
  J_VERSION="1.7.0_17"
  if [ -d /opt/jre${J_VERSION}/bin ]; then
    export LPATH=/opt/jre${J_VERSION}/bin:${LPATH}
  fi
  [ -d /opt/homebrew/opt/openjdk@11/bin ] && export LPATH=/opt/homebrew/opt/openjdk@11/bin:${LPATH}

  JAVA_8_HOME=$(/usr/libexec/java_home -v1.8)
  JAVA_11_HOME=$(/usr/libexec/java_home -v11)
  export JAVA_8_HOME
  export JAVA_11_HOME
  
  alias java8='export JAVA_HOME=$JAVA_8_HOME'
  alias java11='export JAVA_HOME=$JAVA_11_HOME'
}

java_2_path
# default to Java 11
java11