#!/usr/bin/env bash

# postgres_path
# --
# (c) Iver!
# Iván Jaimes <iver@iver.mx>
# --
# Goal: add postgres locations to path

PSQL_VERSION="@10"

postgres_2_path() {
  if [ -d /usr/local/opt/postgresql${PSQL_VERSION}/bin ];
    then export LPATH=/usr/local/opt/postgresql${PSQL_VERSION}/bin:${LPATH}
  fi
}

postgres_2_path
