#!/usr/bin/env bash

# go_path
# --
# (c) Iver!
# Iván Jaimes <iver@iver.mx>
# --
# Goal: add ruby locations to path

umask 0007

ruby_2_path() {
  if [ -d ${HOME}/.rvm/rubies/default/bin ];
    then export LPATH=${HOME}/.rvm/rubies/default/bin:${PATH};
  fi
}

ruby_2_path
