#!/usr/bin/env bash

# rust_path
# --
# (c) Iver!
# Iván Jaimes <iver@iver.mx>
# --
# Goal: add rust locations to path

rust_2_path() {
  if [ -d "${HOME}/.cargo/bin" ];
    then export LPATH=${HOME}/.cargo/bin:${LPATH};
  fi
}

rust_2_path
