#!/bin/sh

# common alias
alias l="ls"
alias ls="ls -F"
alias ll='ls -lhG'  # -l long listing, human readable, no group info
#alias ll="ls -l"
alias la="ll -ah"
alias lt="la -t"
alias lr="lt -r"
alias pw="pwd"

alias ..='cd ..'
alias ...='cd ../..'
alias t='tail -fn'

alias h='history'
alias cdw='cd ~/Workspace'
alias cdg='cd ~/Workspace/go/src'
alias mysql_stop='/usr/local/bin/mysqladmin -u root -p shutdown'
alias mysql_start='/usr/local/bin/mysqld_safe &'
alias publish='python -m SimpleHTTPServer 5000'

alias pg-start='pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/logs/server.log start'
alias pg-stop='pg_ctl stop -m fast'
alias pg-status='pg_ctl status'
alias pg-restart='pg_ctl reload'

alias fpm-start='launchctl load -w /usr/local/opt/php56/homebrew.mxcl.php56.plist'
alias fpm-stop='launchctl unload /usr/local/opt/php56/homebrew.mxcl.php56.plist'

alias purgeallbuilds='rm -rf ~/Library/Developer/Xcode/DerivedData/*'
