#!/bin/sh

# paths
# --
# (c) Iver!
# Iván Jaimes <iver@iver.mx>
#

# This is the user path enviroment file for GNU/Linux.
# See bash_rc or bash_profile for more information.

# input mode
umask 0007

java17 () {
  PATH=/opt/jre1.7.0_17/bin:${LPATH}
}

dart() {
  if [ -d /usr/local/opt/dart@2/bin ]; then
    LPATH=/usr/local/opt/dart@2/bin:${PATH}
    LPATH=.:${LPATH}
    PATH=${LPATH}
  fi
}

ruby() {
  [ -d /Users/iver/.rvm/rubies/default/bin ] && LPATH=/Users/iver/.rvm/rubies/default/bin:${PATH}
  LPATH=.:${LPATH}
  PATH=${LPATH}
}

android(){
  LPATH=${PATH}
  # Android
  [ -d ${HOME}/Library/Android/sdk/tools ] && LPATH=${HOME}/Library/Android/sdk/tools:${LPATH}
  [ -d ${HOME}/Library/Android/sdk/platform-tools ] && LPATH=${HOME}/Library/Android/sdk/platform-tools:${LPATH}
  [ -d /usr/local/android/tools ] && LPATH=/usr/local/android/tools:${LPATH}
  [ -d /usr/local/android/build-tools ] && LPATH=/usr/local/android/build-tools:${LPATH}

  LPATH=.:${LPATH}
  PATH=${LPATH}
}

nosudo_node(){
  # NPM package custom path
  [ -d ${HOME}/.npm-packages ] && export NPM_PACKAGES="${HOME}/.npm-packages"
  [ -d ${NPM_PACKAGES}/lib/node_modules ] && export NODE_PATH="${NPM_PACKAGES}/lib/node_modules:${NODE_PATH}"
}

localpaths () {
  LPATH=${PATH}

  # Other binaries
  [ -d /usr/sbin ] && LPATH=/usr/sbin:${LPATH}
  [ -d /usr/bin ] && LPATH=/usr/bin:${LPATH}
  [ -d /sbin ] && LPATH=/sbin:${LPATH}
  [ -d /bin ] && LPATH=/bin:${LPATH}

  # locals
  [ -d /usr/local/bin ] && LPATH=/usr/local/bin:${LPATH}
  [ -d /usr/local/sbin ] && LPATH=/usr/local/sbin:${LPATH}
  [ -d /opt/local/sbin ] && LPATH=/opt/local/sbin:${LPATH}
  [ -d /opt/local/bin ] && LPATH=/opt/local/bin:${LPATH}
  [ -d ${HOME}/apps ] && LPATH=${HOME}/apps:${LPATH}
  [ -d ${HOME}/bin ] && LPATH=${HOME}/bin:${LPATH}
  [ -d ${HOME}/Library/Python/2.7/bin ] && LPATH=${HOME}/Library/Python/2.7/bin:${LPATH}
  [ -d /usr/local/php5/bin ] && LPATH=/usr/local/php5/bin:${LPATH}
  [ -d /usr/local/mysql/bin ] && LPATH=/usr/local/mysql/bin:${LPATH}
  [ -d /usr/local/opt/postgresql@10/bin ] && LPATH=/usr/local/opt/postgresql@10/bin:${LPATH}
  [ -d /usr/local/sbin/ ] && LPATH=/usr/local/sbin:${LPATH}

  # jenv
  [ -d ${HOME}/.jenv/bin ] && LPATH=${HOME}/.jenv/bin:${LPATH}

  nosudo_node
  [ -d ${NPM_PACKAGES}/bin ] && LPATH=${NPM_PACKAGES}/bin:${LPATH}

  LPATH=.:${LPATH}
  PATH=${LPATH}

}

# Cursor and profile
localpaths
# android
dart
# ruby
