#!/bin/sh

# paths
# --
# (c) Iver!
# Iván Jaimes <iver@iver.mx>
#

# This is the user path enviroment file for GNU/Linux.
# See bash_rc or bash_profile for more information.

# input mode
umask 0007

localpaths () {
  LPATH=${PATH}

  # Android
  [ -d ${HOME}/Library/Android/sdk/tools ] && LPATH=${HOME}/Library/Android/sdk/tools:${LPATH}
  [ -d ${HOME}/Library/Android/sdk/platform-tools ] && LPATH=${HOME}/Library/Android/sdk/platform-tools:${LPATH}
  [ -d /usr/local/android/tools ] && LPATH=/usr/local/android/tools:${LPATH}
  [ -d /usr/local/android/build-tools ] && LPATH=/usr/local/android/build-tools:${LPATH}

  # Other binaries
  [ -d /usr/sbin ] && LPATH=/usr/sbin:${LPATH}
  [ -d /usr/bin ] && LPATH=/usr/bin:${LPATH}
  [ -d /sbin ] && LPATH=/sbin:${LPATH}
  [ -d /bin ] && LPATH=/bin:${LPATH}

  # locals
  [ -d /usr/local/bin ] && LPATH=/usr/local/bin:${LPATH}
  [ -d /opt/local/sbin ] && LPATH=/opt/local/sbin:${LPATH}
  [ -d /opt/local/bin ] && LPATH=/opt/local/bin:${LPATH}
  [ -d ${HOME}/apps ] && LPATH=${HOME}/apps:${LPATH}
  [ -d ${HOME}/bin ] && LPATH=${HOME}/bin:${LPATH}


#  LPATH=/opt/php53/bin:${LPATH}
  LPATH=.:${LPATH}
  PATH=${LPATH}
}

# Cursor and profile
localpaths

# PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
